### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by Karmac** [sissbruecker/linkding-extension#111]
Hello,

I'm opening this issue because I'm unable to troubleshoot a persistent “Connection Error” that occurs when I attempt to configure the extension for the first time.

Some data about my installation:

- Deployment via Docker Compose.
- Authentication is handled by Authelia, with the following environment variables set: `LD_ENABLE_AUTH_PROXY=true` and `LD_AUTH_PROXY_USERNAME_HEADER=HTTP_REMOTE_USER`.
- Using Caddy as a reverse proxy.
- Notably, **when I connect the SingleFile extension to the REST API, it works correctly** and snapshots are uploaded — which makes this issue particularly confusing.

Inspecting service.worker yields no output, as if the extension isn't making any network requests at all.

Any help or guidance would be appreciated. Thanks!

**Comment by kexo1** [comment]
Same here on Firefox extension

**Comment by huyz** [comment]
I have pretty much the same setup as you @Karmac: Docker Compose, Caddy, Authelia.

I've been using the extension for a long time but this is the first time I've enabled Authelia. And my symptom was that whenever I opened the LinkDing extension I would get a Basic Auth pop-up (in which my Authelia credentials wouldn't work).

But sinceas the LinkDing API (which the extension uses) already requires an Authorization token, we just don't need to have Authelia in the mix for API calls at all. So in my Authelia `configuration.yml` I added and it worked:

```yml
access_control:
  rules:
    - domain_regex: '^linkding\.([^.]+)\.com\$'
      resources:
        - '^/bookmarks/new\?'  # Used by iOS Shortcuts
        - '^/api/'  # Used by the LinkDing extension, which already requires an Authorization token
      policy: 'bypass'
```
